import { definePreset } from '@primeuix/themes'
import Aura from '@primeuix/themes/aura'

export const lastbitePreset = definePreset(Aura, {
  semantic: {
    primary: {
      50: '#E6F4EC',
      100: '#CBE8D8',
      200: '#99D0B2',
      300: '#69B98E',
      400: '#45A273',
      500: '#2F8F5B',
      600: '#247247',
      700: '#1D5A39',
      800: '#16442B',
      900: '#102F1E',
      950: '#071A10',
    },
    colorScheme: {
      light: {
        surface: {
          0: '#FFFFFF',
          50: '#FFFCF7',
          100: '#F8F3EA',
          200: '#EDE6DA',
          300: '#DCD2C3',
          400: '#B8AA98',
          500: '#8D7F6E',
          600: '#6F6355',
          700: '#51483E',
          800: '#332D27',
          900: '#1F2933',
          950: '#111820',
        },
        primary: {
          color: '{primary.500}',
          contrastColor: '#FFFFFF',
          hoverColor: '{primary.600}',
          activeColor: '{primary.700}',
        },
        content: {
          background: '{surface.0}',
          hoverBackground: '{surface.50}',
          borderColor: '{surface.200}',
          color: '#1F2933',
          hoverColor: '#111820',
        },
        text: {
          color: '#1F2933',
          hoverColor: '#111820',
          mutedColor: '#5E6A75',
          hoverMutedColor: '#51483E',
        },
        formField: {
          background: '{surface.0}',
          disabledBackground: '{surface.100}',
          filledBackground: '{surface.50}',
          filledHoverBackground: '{surface.50}',
          filledFocusBackground: '{surface.0}',
          borderColor: '{surface.300}',
          hoverBorderColor: '{primary.color}',
          focusBorderColor: '{primary.color}',
          invalidBorderColor: '#E15A3D',
          color: '#1F2933',
          disabledColor: '#8D7F6E',
          placeholderColor: '#5E6A75',
          invalidPlaceholderColor: '#E15A3D',
          floatLabelColor: '#5E6A75',
          floatLabelFocusColor: '{primary.600}',
          floatLabelInvalidColor: '#E15A3D',
          iconColor: '#5E6A75',
          shadow: 'none',
        },
        highlight: {
          background: '#FFF3D6',
          focusBackground: '#F2B84B',
          color: '#1F2933',
          focusColor: '#1F2933',
        },
      },
    },
    focusRing: {
      width: '2px',
      style: 'solid',
      color: '{primary.color}',
      offset: '2px',
      shadow: 'none',
    },
  },
  components: {
    button: {
      root: {
        borderRadius: '8px',
        paddingX: '1rem',
        paddingY: '0.625rem',
        gap: '0.5rem',
        transitionDuration: '150ms',
        primary: {
          background: '{primary.500}',
          hoverBackground: '{primary.600}',
          activeBackground: '{primary.700}',
          borderColor: '{primary.500}',
          hoverBorderColor: '{primary.600}',
          activeBorderColor: '{primary.700}',
          color: '#FFFFFF',
          hoverColor: '#FFFFFF',
          activeColor: '#FFFFFF',
          focusRing: {
            color: '{primary.200}',
            shadow: 'none',
          },
        },
        secondary: {
          background: '#FFF3D6',
          hoverBackground: '#F2B84B',
          activeBackground: '#D89E33',
          borderColor: '#FFF3D6',
          hoverBorderColor: '#F2B84B',
          activeBorderColor: '#D89E33',
          color: '#1F2933',
          hoverColor: '#1F2933',
          activeColor: '#1F2933',
          focusRing: {
            color: '#F2B84B',
            shadow: 'none',
          },
        },
        danger: {
          background: '#E15A3D',
          hoverBackground: '#C9482F',
          activeBackground: '#A93B27',
          borderColor: '#E15A3D',
          hoverBorderColor: '#C9482F',
          activeBorderColor: '#A93B27',
          color: '#FFFFFF',
          hoverColor: '#FFFFFF',
          activeColor: '#FFFFFF',
          focusRing: {
            color: '#F2B8AA',
            shadow: 'none',
          },
        },
      },
    },
    card: {
      root: {
        background: '{surface.0}',
        color: '{text.color}',
        borderRadius: '8px',
        shadow: '0 1px 2px rgb(31 41 51 / 0.08)',
      },
      subtitle: {
        color: '{text.muted.color}',
      },
    },
    tabs: {
      tablist: {
        background: '{surface.0}',
        borderColor: '{surface.200}',
      },
      tab: {
        color: '{text.muted.color}',
        hoverColor: '{primary.600}',
        activeColor: '{primary.600}',
        activeBorderColor: '{primary.500}',
      },
      tabpanel: {
        background: '{surface.0}',
        color: '{text.color}',
      },
    },
  },
})
